[package]
name = "liq-bot"
version = "0.1.8"
license = "MIT"
authors = ["Rodrigo Bronzelle <bronzelle@gmail.com>", "danilo neves cruz <cruzdanilo@gmail.com>"]
edition = "2021"
default-run = "liq-bot"

[features]
liquidation-stats = []
complete-compare = []

[dependencies]
cacache = "10.0.1"
dotenv = "0.15"
ethers = { version = "1.0.0", features = ['ws', 'rustls'] }
eyre = "0.6.8"
futures = "0.3.21"
log = { version = "0.4.6", features = ["std"] }
pin-project-lite = "0.2.9"
pretty_env_logger = "0.4.0"
sentry = { version = "0.29.0", features = ["log"] }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.82"
tokio = { version = "1.19.2", features = ["macros", "rt-multi-thread"] }
tokio-stream = "0.1.8"
